"""Language strings for the Caption AI setup wizard."""

from __future__ import annotations

DEFAULT_LANG = "en"
SUPPORTED_LANGS = ("bn", "en", "hi")

STRINGS = {
    "bn": {
        "title": "Caption AI সেটআপ",
        "choose_lang": "ভাষা বেছে নিন",
        "checking_system": "সিস্টেম যাচাই করা হচ্ছে...",
        "system_ready": "সিস্টেম যাচাই সম্পন্ন",
        "ram": "র‍্যাম",
        "gpu_found": "GPU পাওয়া গেছে",
        "gpu_not_found": "GPU পাওয়া যায়নি (CPU mode)",
        "python_found": "Python পাওয়া গেছে",
        "python_not_found": "Python 3.11 পাওয়া যায়নি — ডাউনলোড হবে",
        "node_found": "Node.js পাওয়া গেছে",
        "node_not_found": "Node.js পাওয়া যায়নি — ডাউনলোড হবে",
        "ffmpeg_found": "FFmpeg পাওয়া গেছে",
        "ffmpeg_not_found": "FFmpeg পাওয়া যায়নি — ডাউনলোড হবে",
        "playwright_found": "Playwright পাওয়া গেছে",
        "playwright_not_found": "Playwright পাওয়া যায়নি — ইন্সটল হবে",
        "continue_btn": "এগিয়ে যান",
        "groq_title": "Groq API Key দিন",
        "groq_placeholder": "gsk_...",
        "groq_hint": "এই Key ছাড়া transcription কাজ করবে না",
        "groq_get_key": "বিনামূল্যে Key নিন →",
        "groq_validate_btn": "Key যাচাই করুন",
        "groq_validating": "Key যাচাই করা হচ্ছে...",
        "groq_valid": "✅ Key সঠিক আছে",
        "groq_invalid": "❌ Key সঠিক নয়। আবার চেষ্টা করুন",
        "install_title": "ইন্সটল হচ্ছে",
        "installing": "ইন্সটল হচ্ছে",
        "install_done": "✅ সম্পন্ন",
        "install_fail": "❌ সমস্যা হয়েছে",
        "error_diagnosis": "সমস্যা বিশ্লেষণ করা হচ্ছে...",
        "dry_run_banner": "🧪 Dry-run mode: কোনো আসল install বা file change হবে না",
        "launch_title": "সব প্রস্তুত!",
        "launch_btn": "Caption AI চালু করুন 🚀",
        "launch_hint": "Launch চাপলে backend ও frontend চালু হবে",
        "dry_run_launch_btn": "Wizard বন্ধ করুন",
        "dry_run_launch_hint": "Dry-run সম্পন্ন। আসল install এর জন্য dry-run বন্ধ করে আবার চালান।",
        "close_apps": "⚠️ Chrome, VS Code বন্ধ করুন — RAM খালি রাখুন",
        "step_python": "Python 3.11 ইন্সটল",
        "step_venv": "Virtual Environment তৈরি",
        "step_torch": "PyTorch ইন্সটল",
        "step_heavy": "Heavy packages ইন্সটল",
        "step_remaining": "বাকি Python packages ইন্সটল",
        "step_node": "Node.js ইন্সটল",
        "step_ffmpeg": "FFmpeg ইন্সটল",
        "step_frontend": "Frontend dependencies ইন্সটল",
        "step_playwright": "Playwright + Chromium ইন্সটল",
        "step_env": ".env ফাইল তৈরি",
        "step_startbat": "start.bat তৈরি",
        "finished": "সেটআপ সম্পন্ন",
        "failed_prefix": "ধাপ ব্যর্থ হয়েছে",
        "open_key_site": "Key Site খুলুন",
        "groq_skip": "Skip করুন →",
        "groq_skip_warn": "⚠️ Key ছাড়া এগিয়ে যাচ্ছেন — পরে .env ফাইলে GROQ_API_KEY দিতে হবে",
    },
    "en": {
        "title": "Caption AI Setup",
        "choose_lang": "Choose Language",
        "checking_system": "Checking your system...",
        "system_ready": "System check complete",
        "ram": "RAM",
        "gpu_found": "GPU detected",
        "gpu_not_found": "GPU not found (CPU mode)",
        "python_found": "Python detected",
        "python_not_found": "Python 3.11 not found — will be downloaded",
        "node_found": "Node.js detected",
        "node_not_found": "Node.js not found — will be downloaded",
        "ffmpeg_found": "FFmpeg detected",
        "ffmpeg_not_found": "FFmpeg not found — will be downloaded",
        "playwright_found": "Playwright detected",
        "playwright_not_found": "Playwright not found — will be installed",
        "continue_btn": "Continue",
        "groq_title": "Enter Groq API Key",
        "groq_placeholder": "gsk_...",
        "groq_hint": "Transcription will not work without this key",
        "groq_get_key": "Get a free key →",
        "groq_validate_btn": "Validate Key",
        "groq_validating": "Validating key...",
        "groq_valid": "✅ Key is valid",
        "groq_invalid": "❌ Invalid key. Please try again",
        "install_title": "Installing",
        "installing": "Installing",
        "install_done": "✅ Done",
        "install_fail": "❌ Failed",
        "error_diagnosis": "Diagnosing the issue...",
        "dry_run_banner": "🧪 Dry-run mode: no real installs or file changes will be made",
        "launch_title": "Everything is ready!",
        "launch_btn": "Launch Caption AI 🚀",
        "launch_hint": "Launch will start backend and frontend",
        "dry_run_launch_btn": "Close Wizard",
        "dry_run_launch_hint": "Dry-run completed. Run again without dry-run for real installation.",
        "close_apps": "⚠️ Close Chrome and VS Code to free RAM",
        "step_python": "Install Python 3.11",
        "step_venv": "Create virtual environment",
        "step_torch": "Install PyTorch",
        "step_heavy": "Install heavy packages",
        "step_remaining": "Install remaining Python packages",
        "step_node": "Install Node.js",
        "step_ffmpeg": "Install FFmpeg",
        "step_frontend": "Install frontend dependencies",
        "step_playwright": "Install Playwright + Chromium",
        "step_env": "Create .env file",
        "step_startbat": "Create start.bat",
        "finished": "Setup completed",
        "failed_prefix": "Step failed",
        "open_key_site": "Open key site",
        "groq_skip": "Skip →",
        "groq_skip_warn": "⚠️ Continuing without key — you must add GROQ_API_KEY to .env later",
    },
    "hi": {
        "title": "Caption AI सेटअप",
        "choose_lang": "भाषा चुनें",
        "checking_system": "सिस्टम जांचा जा रहा है...",
        "system_ready": "सिस्टम जांच पूरी हुई",
        "ram": "रैम",
        "gpu_found": "GPU मिला",
        "gpu_not_found": "GPU नहीं मिला (CPU mode)",
        "python_found": "Python मिला",
        "python_not_found": "Python 3.11 नहीं मिला — डाउनलोड होगा",
        "node_found": "Node.js मिला",
        "node_not_found": "Node.js नहीं मिला — डाउनलोड होगा",
        "ffmpeg_found": "FFmpeg मिला",
        "ffmpeg_not_found": "FFmpeg नहीं मिला — डाउनलोड होगा",
        "playwright_found": "Playwright मिला",
        "playwright_not_found": "Playwright नहीं मिला — इंस्टॉल होगा",
        "continue_btn": "आगे बढ़ें",
        "groq_title": "Groq API Key दर्ज करें",
        "groq_placeholder": "gsk_...",
        "groq_hint": "इस key के बिना transcription काम नहीं करेगा",
        "groq_get_key": "मुफ्त Key लें →",
        "groq_validate_btn": "Key जांचें",
        "groq_validating": "Key जांची जा रही है...",
        "groq_valid": "✅ Key सही है",
        "groq_invalid": "❌ Key सही नहीं है। फिर कोशिश करें",
        "install_title": "इंस्टॉल हो रहा है",
        "installing": "इंस्टॉल हो रहा है",
        "install_done": "✅ पूरा हुआ",
        "install_fail": "❌ समस्या हुई",
        "error_diagnosis": "समस्या का विश्लेषण किया जा रहा है...",
        "dry_run_banner": "🧪 Dry-run mode: कोई असली install या file change नहीं होगा",
        "launch_title": "सब तैयार है!",
        "launch_btn": "Caption AI शुरू करें 🚀",
        "launch_hint": "Launch दबाने पर backend और frontend शुरू होंगे",
        "dry_run_launch_btn": "Wizard बंद करें",
        "dry_run_launch_hint": "Dry-run पूरा हुआ। असली install के लिए dry-run बंद करके दोबारा चलाएं।",
        "close_apps": "⚠️ RAM खाली रखने के लिए Chrome और VS Code बंद करें",
        "step_python": "Python 3.11 इंस्टॉल",
        "step_venv": "Virtual environment बनाना",
        "step_torch": "PyTorch इंस्टॉल",
        "step_heavy": "Heavy packages इंस्टॉल",
        "step_remaining": "बाकी Python packages इंस्टॉल",
        "step_node": "Node.js इंस्टॉल",
        "step_ffmpeg": "FFmpeg इंस्टॉल",
        "step_frontend": "Frontend dependencies इंस्टॉल",
        "step_playwright": "Playwright + Chromium इंस्टॉल",
        "step_env": ".env फाइल बनाना",
        "step_startbat": "start.bat बनाना",
        "finished": "सेटअप पूरा हुआ",
        "failed_prefix": "स्टेप फेल हुआ",
        "open_key_site": "Key साइट खोलें",
        "groq_skip": "Skip करें →",
        "groq_skip_warn": "⚠️ Key के बिना आगे बढ़ रहे हैं — बाद में .env में GROQ_API_KEY जोड़ना होगा",
    },
}


def get_text(lang: str, key: str) -> str:
    """Return localized text with safe fallback to English and then key."""
    lang_pack = STRINGS.get(lang) or STRINGS[DEFAULT_LANG]
    if key in lang_pack:
        return lang_pack[key]
    return STRINGS[DEFAULT_LANG].get(key, key)


def get_lang_pack(lang: str) -> dict[str, str]:
    """Return the whole language pack for the selected language."""
    return STRINGS.get(lang, STRINGS[DEFAULT_LANG])
